apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-app
  template:
    metadata:
      labels:
        app: email-app
    spec:
      containers:
        - name: email-app
          image: omkarnerale18/email-app:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_HOST
              value: "mongo"  # see next step
            - name: MONGO_PORT
              value: "27017"
